{% set name = "tomlkit" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tomlkit-{{ version }}.tar.gz
  sha256: 30d54c0b914e595f3d10a87888599eab5321a2a69abc773bbefff51599b72db6

build:
  number: 0
  noarch: python
  script:
    # Somehow, when pyproject.toml is present, it requires poetry on Windows.
    # However, even with that dependency satisfied, we get:
    # "tomlkit cannot depend on itself"
    - del pyproject.toml  # [win]
    - rm pyproject.toml  # [not win]
    # Causes ClobberWarnings. Remove after https://github.com/sdispater/tomlkit/issues/69
    - rm -rf tests  # [not win]
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0a9
    - python
    - setuptools
    - wheel
  run:
    - python >=3.6

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - tomlkit

about:
  home: https://github.com/sdispater/tomlkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Style preserving TOML library
  dev_url: https://github.com/sdispater/tomlkit
  doc_url: https://github.com/sdispater/tomlkit/blob/master/README.md
  doc_source_url: https://github.com/sdispater/tomlkit/blob/master/docs/quickstart.rst

extra:
  recipe-maintainers:
    - ocefpaf
